### ISSUE TITLE
能否提供对索引模式添加的图片文件的支持

### ISSUE THREAD

**Issue by LSP0123** [Ai-desu-2333/Pixiv2Billfish#2]
请求修改对作者tag的处理，部分作者会在cm期间将id改为“id@事项”的格式，请在写入id时过滤掉@后的文字

**Comment by Ai-desu-2333** [comment]
可以实现，有些作者id默认会包含@，或者包含多个@，没法实现准确判断@及之后内容代表的含义:face_with_spiral_eyes:，
所以打算仅去除id中最后一个@后的内容（包含@），
如果@在id中位于前三位或后三位，则进行保留，
例如 [uid=17581755](https://www.pixiv.net/users/17581755) 这位画师 id为 **T@ke-G/お仕事募集中** 暴力过滤@或者/会导致id不完整。

**Comment by LSP0123** [comment]
昨天根据使用情况反馈了部分billfish的bug给他们，顺便问一下，有考虑将图片网址添加到数据库里吗？
![image](https://user-images.githubusercontent.com/31061624/214218709-95239fd5-6834-4137-99a1-27ea106a7e18.png)
还有两个问题，一是备注区域有时候会超过billfish最大字符限制,例如[pid=103094865](https://www.pixiv.net/artworks/103094865)
![image](https://user-images.githubusercontent.com/31061624/214219925-decceb2c-bd5c-413a-87e7-b846f39db40b.png)
，建议控制下字符数，或者反馈给billfish？二是作者的tag使用Artist:ID形式时，在billfish里不能直接搜索ID标签，这个问题我昨天已经反馈给billfish了.

**Comment by Ai-desu-2333** [comment]
1. 关于添加图片网址，因为自己没有需要，就没有写，有需要的话我回头可以写一下，加个开关进行控制；
2. 关于备注区域最大字符限制问题，观察了一下，发现billfish吧最大字符数限制在了400，如果使用暴力截断，将和billfish对备注的操作一致，所以目前有一种思路是删除 `BookMark:` 行，并尝试删除出现的所有url，如果你有其他想法，欢迎交流；
3. 作者的tag使用Artist:ID形式是为了我自己便于分辨，搜索则需要形如 `Artist:弱電波( ` 这样进行搜索（没错，`弱電波(@JackDempa)`中@后的内容被过滤了），如果觉得Artist:ID不合适，可以在源文件中搜索 `tag_list = ["Artist:" + artist]` 将其改为 `tag_list = [artist]` 这样作者标签将只含作者ID（其实测试了一下，billfish的tag是支持模糊搜索的）。

**Comment by LSP0123** [comment]
1，非常感谢添加功能；
2，我的想法是删除`bookmark:`行后面的`comment`，然后利用网址去原网页查看，例如水蛇的[PID:104144221](https://www.pixiv.net/artworks/104144221)这种反而是如何处理都不太好，不如自行去原页面查看；
3，是我昨天没有描述清楚问题，抱歉。Artist:ID作为作者ID的tag我认为是正确的，但是billfish那边的搜索有点问题，我正在和billfish反馈这个搜索问题，可能是“:”带来的错误，如下图中`Artist:Anmi`就不能通过anmi搜索到。（我正在向billfish反馈添加“tag批量分组”功能以及这个bug，
![image](https://user-images.githubusercontent.com/31061624/214457730-09f75af3-71ca-4e48-b545-64266ca1a889.png)
再次感谢dalao付出，顺便问一下，有没有做danbooru的tag的想法

**Comment by Ai-desu-2333** [comment]
dalao我称不上，你过奖了，

针对1、2，删除了备注中的bookmark项，添加了对链接的写入，直接在本地进行拼接，即便404了也会加上形如`https://www.pixiv.net/artworks/PID`这样的链接，需要观察是否可行，没有对备注的字符数限制进行处理；

3经过测试，billfish确实存在这个问题，等待billfish进行处理。

**Comment by LSP0123** [comment]
不是删bookmark啊，comment才是导致备注的字符数过长的原因

**Comment by Ai-desu-2333** [comment]
哦抱歉，看串了:dizzy_face:
因为我希望备注拥有`comment`行，所以不打算删除
你需要不写入`comment`行的话，请在源文件中定位至`get_note`函数：
https://github.com/Ai-desu-2333/Pixiv2Billfish/blob/8be44d14297ab803b356a59de79ea5c248652c47/Pixiv2Billfish.py#L196-L241

将本函数中`# 添加描述` 至 `note = re.sub("'", "''", note)`中间的内容删除，
即实现不添加`comment`行，

之后在`note = re.sub("'", "''", note)`上方插入
`note += "Bookmark:" + json_data["body"]["bookmarkCount"] + "\r\n"`
即实现添加`Bookmark`行。
<details><summary>修改后的本函数完整代码如下</summary>

```python
 def get_note(pid):
  """
  从pixiv api获取pid illustTitle userName userId illustComment
  :params pid: pixiv插画id
  :return: "illustTitle userName userId  illustComment" or “”
  """
  resp = baseRequest(
      options={"url": f"{temp_url}{pid}"}
  )

  if not resp:
      logger.warning("Warning:{}".format(pid + ' 获取信息异常'))
      return ""
  elif resp.status_code == 404:
      logger.warning("Warning:{}".format(pid + ' 该作品已被删除，或作品ID不存在。'))
      return "Error:404"

  json_data = json.loads(resp.text)
  if not json_data["error"]:
      # 添加标题
      note = "Title:" + json_data["body"]["illustTitle"] + "\r\n"  # 获取标题
      # 添加作者
      artist = json_data["body"]["userName"]
      if artist.rfind('@') != -1 and 2 <= artist.rfind('@') <= len(artist) - 3:
          artist = artist[0:artist.rfind('@')]
      else:
          artist = artist
      note += "Artist:" + artist + "\r\n"
      # 添加UID
      note += "UID:" + json_data["body"]["userId"] + "\r\n"

      # 添加Bookmark
      note += "Bookmark:" + json_data["body"]["bookmarkCount"] + "\r\n"

      note = re.sub("'", "''", note)
      return note
  else:
      return ""

```

</details>

**Comment by LSP0123** [comment]
我也想保留comment的，但是billfish有字数限制，我在反馈这个问题，看billfish那边能不能解除这个限制
非常感谢指导
