### ISSUE TITLE
关于在使用steam++开启hosts代理时不能获取页面的问题

### ISSUE THREAD

**Issue by LSP0123** [Ai-desu-2333/Pixiv2Billfish#3]
环境:windows11,edge浏览器.开启[steam++](https://github.com/BeyondDimension/SteamTools)的hosts加速模式.

浏览器可以正常访问`https://www.pixiv.net/ajax/illust/pid`页面,但是脚本不能访问,不论使用uwp版python还是exe版python运行脚本均无法访问和获取信息.
log如见附件
[2023-01-24_13-46-20_098762.log](https://github.com/Ai-desu-2333/Pixiv2Billfish/files/10486697/2023-01-24_13-46-20_098762.log)

**Comment by Ai-desu-2333** [comment]
经测试在steam++的hosts加速模式下使用没有问题，
[V0.1.1](https://github.com/Ai-desu-2333/Pixiv2Billfish/releases/tag/V0.1.1)版本更改了代理的使用逻辑，增加了`useProxies` 参数，默认为1，代表使用http代理，使用steam++的hosts加速模式，需要将`useProxies` 设置为0，
之后将修改默认值为0，并将提示加入readme。

**Comment by LSP0123** [comment]
非常感谢dalao
