### ISSUE TITLE
请求支持billfish3.0

### ISSUE THREAD

**Issue by LSP0123** [Ai-desu-2333/Pixiv2Billfish#5]
billfish发布了3.0，数据库部分有改动，请添加3.0支持

**Comment by Ai-desu-2333** [comment]
已了解，目前观察了一下，发现针对本程序涉及到的数据库表，有了一些更改，在此大概记录一下：
1. 标签表更换`  bf_tag -> bf_tag_v2  `
2. `bf_tag_v2`中增加了`pid`用来记录标签的层级关系，`pid`为其父级标签的`id`，标签组疑似被取代
3. Billfish程序中备注不再限制字数
4. 备注涉及的相关数据库表暂时没发现改动

Todo:
- 增加对3.0版本数据库的识别和支持
- 针对3.0版本数据库
  - 添加`Artist`父标签，所有作者标签归属其中
  - 作者标签格式进行更改`Artist:ID -> ID`

**Comment by LSP0123** [comment]
3.0中可以录入重复标签了，请注意

**Comment by Ai-desu-2333** [comment]
已更新[v0.1.2](https://github.com/Ai-desu-2333/Pixiv2Billfish/releases/tag/V0.1.2)
增加了对新版数据库的支持，欢迎尝鲜和反馈BUG（记得先备份源数据库）
