### ISSUE TITLE
update_artist_tag中对作者名称中的特殊字符缺少过滤

### ISSUE THREAD

**Issue by HelloCard** [Ai-desu-2333/Pixiv2Billfish#6]
679 - UPDATE bf_tag_v2 SET name = 'Mi'yuki' , pid = '5005' WHERE id = '3646'
688 - Exception:near "yuki": syntax error
如上错误，请考虑在构造数据库操作指令前对特定字符进行过滤。

**Comment by HelloCard** [comment]
我改成这样，可以解决问题：
for i in artistlist:
    safeName = i["name"].replace("'","''")
    cursor.execute("UPDATE bf_tag_v2 SET name = '" + safeName + "' , pid = '" + i["pid"] + "' WHERE id = '" + i["id"] + "'")

**Comment by Ai-desu-2333** [comment]
感谢反馈，已经进行处理；
原因是增加对新版本数据库支持时忘记了处理单引号，通过修改了SQL语句的构成方法来避免这个问题；
（提交了才发现相关旧代码忘删了，算了不影响使用，下次提交再说吧）

**Comment by HelloCard** [comment]
问题已修复。
